apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: scheduler
spec:
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - image: suhasedunet/scheduler:v4.0
        name: scheduler-container
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DATABASE
          value: s_ink
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 9090
