version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: verilumaci/maven-3.3.9
    steps:
      - checkout # check out the code in the project directory             
      - run:
          name: Build and Install web modules
          command: mvn clean install -Pweb
      - run:
          name: Build and Install scheduler module
          command: mvn clean install -Pscheduler           
      - run:
          name: Prepare Archive
          command: |
            mkdir -p artifacts
            cp endpoints/target/endpoints-*.jar artifacts/
            cp services/target/services-*.jar artifacts/
            cp persistance/target/persistance-*.jar artifacts/
            cp scheduler/target/scheduler-*.jar artifacts/
            ls -lrt artifacts
      - store_artifacts:   
          path: artifacts
